# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh-Hans:
  languageCode: zh-Hans
  title: æ¾³æªæ£®æ•°æ™ºç§‘æŠ€æœåŠ¡
  params:
    description: æ•°æ™ºå¹³å°ä¸ç»¿è‰²é‡‘èç§‘æŠ€çš„åˆ›æ–°è®¾è®¡
  menu:
    main:
      - name: ğŸ“ªè¿ç»œ
        url: '#contact'
        weight: 6
      - name: æˆå‘˜
        url: 'people'
        weight: 5
      - name: å‘å‘
        url: 'publication'
        weight: 3
      - name: ç²¾å‡†è„±ç¢³ä¹‹æ—…
        url: 'tour'
        weight: 2
      - name: åŒåŒ–ååŒå‘å±•
        url: 'post'
        weight: 1
  en:
    params:
    title: Oxford Roadmapping
    weight: 2
  zh-Hant:
    title: æ¾³æªæ£®æ•¸æ™ºç§‘æŠ€æœå‹™
    weight: 3

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title: Oxford Roadmapping  (Oxon8)
  params:
    description: Innovate with Designs of Smart Platforms and Green FinTech, on a mission to reduce gigatones of GHG emissions by transforming how carbon neutrality information flows change business operations and supply chains
  menu:
    main:
      - name: people
        url: 'people'
        weight: 3
      - name: tour
        url: 'tour'
        weight: 2
      - name: news
        url: 'post'
        weight: 1
  zh:
    params:
    title: æ¾³æªæ£®æ•°æ™º
    weight: 1
  zh-Hans:
    params:
    title: æ¾³æªæ£®æ•°æ™ºç§‘æŠ€æœåŠ¡
    weight: 2
  zh-Hant:
    title: æ¾³æªæ£®æ•¸æ™ºç§‘æŠ€æœå‹™
    weight: 3

zh-Hant:
  languageCode: zh-Hant
  languageName: ä¸­æ–‡ (æ­£é«”)
  title: æ¾³æªæ£®æ•¸æ™ºç§‘æŠ€æœå‹™
  params:
    description: æ•¸æ™ºå¹³å°èˆ‡ç¶ è‰²é‡‘èç§‘æŠ€çš„å‰µæ–°è¨­è¨ˆ
  menu:
      main:
      - name: è¯çµ¡
        url: '#contact'
        weight: 6
      - name: æˆ‘å€‘æˆå“¡
        url: 'people'
        weight: 5
      - name: å‘è¡¨
        url: 'publication'
        weight: 3
      - name: ç²¾æº–è„«ç¢³ä¹‹æ—…
        url: 'tour'
        weight: 2
      - name: ç¶ è‰²åŒ–æ•¸ä½åŒ–è½‰å‹ç™¼å±•
        url: 'post'
        weight: 1
  en:
    params:
    title: Oxford Roadmapping
    weight: 2
  zh:
    title: æ¾³æªæ£®æ•°æ™ºç§‘æŠ€æœåŠ¡
    weight: 3
